FROM python:3.11-bookworm

WORKDIR /app

COPY requirements.txt ./

RUN python3 -m pip install -r requirements.txt

COPY . ./

EXPOSE 5000

CMD [ "python3", "-m", "flask", "--app", "server", "run", "--host", "0.0.0.0" ]
